[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.pdf"
    [headers.values]
      Content-Type = "application/pdf"
      Content-Disposition = "inline; filename=\"lacunafoodmenu.pdf\""